{% set name = "towncrier" %}
{% set version = "21.3.0" %}
{% set sha256 = "6eed0bc924d72c98c000cb8a64de3bd566e5cb0d11032b73fcccf8a8f956ddfe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - towncrier = towncrier._shell:cli

requirements:
  host:
    - incremental
    - pip
    - python >=2.7
  run:
    - click
    - click-default-group
    - incremental
    - jinja2
    - python >=2.7
    - toml

test:
  imports:
    - towncrier
  commands:
    - towncrier --help

about:
  home: https://github.com/twisted/towncrier
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Building newsfiles for your project

  description: |
    towncrier is a utility to produce useful, summarised news files for your project.
    Rather than reading the Git history as some newer tools to produce it, or having one single
    file which developers all write to, towncrier reads "news fragments" which contain
    information useful to end users.

extra:
  recipe-maintainers:
    - kain88-de
    - ericpre
